package pdf

import (
	"bytes"
	"context"
	"flag"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var updateGolden = flag.Bool("update", false, "regenerate synthetic golden + fixture files")

const corpusRoot = "testdata/corpus"

type compareMode int

const (
	compareExact      compareMode = iota // synthetic: byte-exact
	compareNormalized                    // real: whitespace-normalized substring
)

// corpusEntry is the single machine-readable source of truth for one fixture.
// README.md mirrors Source/License/Purpose for human readers.
type corpusEntry struct {
	Path      string      // relative to corpusRoot, e.g. "plaintext/hello-ascii.pdf"
	Golden    string      // relative golden path; "" = bench-only fixture (no golden)
	Synthetic bool        // true => generated by TestCorpusRegenerate
	Compare   compareMode // exact (synthetic) or normalized (real)
	Password  string      // for encrypted fixtures; "" otherwise
	Feature   string      // descriptive feature tag this fixture supports
	Source    string      // provenance URL or "synthetic"
	License   string      // "synthetic" | "US-Gov PD (17 USC 105)" | "CC0" | "Public domain (author d. >70y)"
	Purpose   string
}

// corpusManifest is the authoritative list. Adding a .pdf without an entry here fails
// TestCorpusManifestComplete.
var corpusManifest = []corpusEntry{
	{
		Path: "plaintext/hello-ascii.pdf", Golden: "plaintext/hello-ascii.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "corpus-baseline",
		Source: "synthetic", License: "synthetic",
		Purpose: "ASCII plain-text extraction baseline",
	},
	{
		Path: "styled/multifont.pdf", Golden: "styled/multifont.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "corpus-baseline",
		Source: "synthetic", License: "synthetic",
		Purpose: "Styled (multi-font) text extraction baseline",
	},
	// Real, verified, public-domain multilingual fixtures (already stored under
	// testdata/corpus/; see testdata/corpus/README.md for full provenance/license).
	// Golden snippets are hand-authored body-text passages; compareNormalized.
	{
		Path: "cjk/udhr-zh-hans.pdf", Golden: "cjk/udhr-zh-hans.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "corpus-baseline",
		Source: "OHCHR UDHR (chn)", License: "Public domain (UDHR)",
		Purpose: "Simplified Chinese extraction",
	},
	{
		Path: "cjk/irs-p850-zh-hant.pdf", Golden: "cjk/irs-p850-zh-hant.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "corpus-baseline",
		Source: "IRS Pub 850 EN-ZH-T", License: "US-Gov PD (17 USC 105)",
		Purpose: "Traditional Chinese extraction",
	},
	{
		Path: "cjk/udhr-ja.pdf", Golden: "cjk/udhr-ja.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "corpus-baseline",
		Source: "OHCHR UDHR (jpn)", License: "Public domain (UDHR)",
		Purpose: "Japanese extraction",
	},
	{
		Path: "cjk/udhr-ko.pdf", Golden: "cjk/udhr-ko.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "corpus-baseline",
		Source: "OHCHR UDHR (kkn)", License: "Public domain (UDHR)",
		Purpose: "Korean extraction",
	},
	{
		Path: "cyrillic/udhr-ru.pdf", Golden: "cyrillic/udhr-ru.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "encoding-fallback baseline",
		Source: "OHCHR UDHR (rus)", License: "Public domain (UDHR)",
		Purpose: "Russian (Cyrillic) extraction baseline for v0.8",
	},
	{
		Path: "bench/synthetic-multipage.pdf", Golden: "", Synthetic: true,
		Compare: compareExact, Feature: "corpus-baseline", Source: "synthetic", License: "synthetic",
		Purpose: "Synthetic multi-page benchmark corpus",
	},
	// Table-detection spike fixtures (acquired 2026-06-07; extraction verified
	// with Words()/Lines() probes before commit — provenance in README.md).
	{
		Path: "tables/nist-hb44-appc-2026.pdf", Golden: "tables/nist-hb44-appc-2026.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-spike",
		Source: "NIST Handbook 44 (2026) Appendix C", License: "US-Gov PD (17 USC 105)",
		Purpose: "Axis-aligned unit-conversion tables; clean text layer (spike accuracy gate)",
	},
	{
		Path: "tables/irs-p55b-2025-excerpt.pdf", Golden: "tables/irs-p55b-2025-excerpt.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-spike",
		Source: "IRS Data Book 2025 (Pub 55-B) pp. 40-55, qpdf excerpt", License: "US-Gov PD (17 USC 105)",
		Purpose: "Financial statistics tables; numeric columns extract, some labels unmapped",
	},
	// Table-detection false-positive gate fixtures: dense 3-column Federal
	// Register notices with ZERO tables — a detector must return nothing here.
	{
		Path: "multicolumn/fr-2024-06543.pdf", Golden: "multicolumn/fr-2024-06543.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-spike",
		Source: "Federal Register 89 FR 21528 (2024-06543), govinfo.gov", License: "US-Gov PD (17 USC 105)",
		Purpose: "Dense 3-column body text, no tables (spike false-positive gate)",
	},
	{
		Path: "multicolumn/fr-2024-01353.pdf", Golden: "multicolumn/fr-2024-01353.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-spike",
		Source: "Federal Register 89 FR 4633 (2024-01353), govinfo.gov", License: "US-Gov PD (17 USC 105)",
		Purpose: "Dense 3-column body text, no tables (spike false-positive gate)",
	},
	// Hard-PDF fixtures discovered during table-fixture acquisition: real
	// US-Gov financial PDFs that defeat current extraction; no goldens — they
	// document the gap until future fallback-encoding work closes it.
	{
		Path: "hard/bea-dici0724.pdf", Golden: "",
		Synthetic: false, Compare: compareNormalized, Feature: "hard-pdf",
		Source: "BEA Direct Investment by Country and Industry (Jul 2024)", License: "US-Gov PD (17 USC 105)",
		Purpose: "Missing-ToUnicode subset fonts: table geometry intact, text unmappable",
	},
	{
		Path: "hard/irs-p1040-tax-tables-excerpt.pdf", Golden: "",
		Synthetic: false, Compare: compareNormalized, Feature: "hard-pdf",
		Source: "IRS Pub 1040 Tax Tables pp. 3-4, qpdf excerpt", License: "US-Gov PD (17 USC 105)",
		Purpose: "Zero-advance glyph widths (W=0) plus partial ToUnicode loss",
	},
	// Synthetic extraction-readiness signal fixtures.
	// Consumers: the extraction quality score and the image/scanned-page classifier.
	// Golden cells reflect the EMPIRICAL classification (probe run at implementation):
	// image-only pages and the truncated stream extract no usable plain text (Golden:"");
	// the rest extract deterministic text and are byte-locked. wantErr/HasText live in
	// signalExpectations (corpus_signals_test.go), keyed on ExtractionSummary, which can
	// differ from the GetPlainText-keyed Golden decision (truncated: Golden:"" yet
	// ExtractionSummary recovers to HasText=true — a silent-ok gap the quality score will close).
	{
		Path: "signals/image-full-bleed.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "signal-image-classifier",
		Source: "synthetic", License: "synthetic",
		Purpose: "Full-bleed image-only page (coverage ~1.0); image_only signal",
	},
	{
		Path: "signals/image-thumbnail.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "signal-image-classifier",
		Source: "synthetic", License: "synthetic",
		Purpose: "Thumbnail-only image page (coverage ~0.0074); v1 indistinguishable from full-bleed",
	},
	{
		Path: "signals/image-thumbnail-text.pdf", Golden: "signals/image-thumbnail-text.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-image-classifier",
		Source: "synthetic", License: "synthetic",
		Purpose: "Small image + body text; mixed page, not image-only",
	},
	{
		Path: "signals/text-artifact-only.pdf", Golden: "signals/text-artifact-only.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-image-classifier",
		Source: "synthetic", License: "synthetic",
		Purpose: "Artifact-only sparse text (page number at extremity); v1 reports HasText=true",
	},
	{
		Path: "signals/malformed-unclosed-bt.pdf", Golden: "signals/malformed-unclosed-bt.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-malformed-stream",
		Source: "synthetic", License: "synthetic",
		Purpose: "Unclosed BT (no ET); tolerated, deterministic partial extraction, no panic",
	},
	{
		Path: "signals/malformed-mismatched-qq.pdf", Golden: "signals/malformed-mismatched-qq.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-malformed-stream",
		Source: "synthetic", License: "synthetic",
		Purpose: "Excess Q (q/Q imbalance); tolerated, deterministic extraction, no panic",
	},
	{
		Path: "signals/malformed-truncated.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "signal-malformed-stream",
		Source: "synthetic", License: "synthetic",
		// Realized as an empty-TJ operator (deterministic panic trigger), NOT a
		// byte-level cut-off stream — slice-1 ships no genuinely-truncated fixture.
		Purpose: "Malformed operator (TJ w/o array); GetPlainText errors, ExtractionSummary recovers (silent-ok gap), no panic",
	},
}

func corpusPath(rel string) string { return filepath.Join(corpusRoot, filepath.FromSlash(rel)) }

func loadCorpus(t *testing.T, e corpusEntry) *Reader {
	t.Helper()
	data, err := os.ReadFile(corpusPath(e.Path))
	if err != nil {
		t.Fatalf("read fixture %s: %v", e.Path, err)
	}
	if e.Password != "" {
		r, err := NewReaderEncrypted(bytes.NewReader(data), int64(len(data)), func() string { return e.Password })
		if err != nil {
			t.Fatalf("open encrypted fixture %s: %v", e.Path, err)
		}
		return r
	}
	r, err := OpenBytes(data)
	if err != nil {
		t.Fatalf("open fixture %s: %v", e.Path, err)
	}
	return r
}

func extractPlainText(t *testing.T, r *Reader) string {
	t.Helper()
	rd, err := r.GetPlainText(context.Background())
	if err != nil {
		t.Fatalf("GetPlainText: %v", err)
	}
	b, err := io.ReadAll(rd)
	if err != nil {
		t.Fatalf("read extracted text: %v", err)
	}
	return string(b)
}

var wsRun = strings.NewReplacer("\r", " ", "\n", " ", "\t", " ")

func normalize(s string) string {
	return strings.Join(strings.Fields(wsRun.Replace(s)), " ")
}

// assertGolden checks extraction output `got` against golden bytes `want` per the
// entry's compare mode. Split out of TestCorpusGolden to keep that test's cyclomatic
// complexity within the gocyclo budget.
func assertGolden(t *testing.T, e corpusEntry, got string, want []byte) {
	t.Helper()
	switch e.Compare {
	case compareExact:
		if got != string(want) {
			t.Errorf("%s: exact mismatch\n got: %q\nwant: %q", e.Path, got, string(want))
		}
	case compareNormalized:
		// The golden holds one required snippet per non-empty line; EVERY one must
		// appear in the normalized extraction. Multiple body-text snippets (not just a
		// title) make this a real regression sentinel: an extractor that returns only
		// the heading but drops body text fails. An empty or whitespace-only golden
		// yields zero snippets and is rejected, because strings.Contains(x, "") is
		// vacuously true (D2/D3).
		gotNorm := normalize(got)
		var checked int
		for _, line := range strings.Split(string(want), "\n") {
			snip := normalize(line)
			if snip == "" {
				continue
			}
			checked++
			if !strings.Contains(gotNorm, snip) {
				t.Errorf("%s: required snippet not found in extraction\nsnippet: %q\ngot: %q",
					e.Path, snip, gotNorm)
			}
		}
		if checked == 0 {
			t.Fatalf("%s: normalized golden %s has no non-empty snippets — refusing to pass vacuously",
				e.Path, e.Golden)
		}
	default:
		// An out-of-range Compare would otherwise extract + read the golden but run no
		// assertion, making the entry look covered while regressions stay invisible.
		// TestCorpusManifestComplete also rejects this statically.
		t.Fatalf("%s: unknown compare mode %d", e.Path, int(e.Compare))
	}
}

func TestCorpusGolden(t *testing.T) {
	for _, e := range corpusManifest {
		if e.Golden == "" {
			continue // bench-only fixture
		}
		t.Run(e.Path, func(t *testing.T) {
			got := extractPlainText(t, loadCorpus(t, e))
			goldenFile := corpusPath(e.Golden)
			// -update regenerates synthetic+exact goldens only — never real/normalized
			// goldens, to avoid leaking PII from a real PDF's body (D3). The Synthetic
			// guard is belt-and-braces: a real entry mislabelled compareExact would
			// otherwise have its hand-authored golden overwritten by full extraction.
			// TestCorpusManifestComplete additionally rejects that mislabelling.
			if *updateGolden && e.Synthetic && e.Compare == compareExact {
				if err := os.WriteFile(goldenFile, []byte(got), 0o600); err != nil {
					t.Fatalf("update golden %s: %v", e.Golden, err)
				}
				return
			}
			//nolint:gosec // G304: goldenFile is a fixed corpus path from the manifest, not user input
			want, err := os.ReadFile(goldenFile)
			if err != nil {
				t.Fatalf("read golden %s: %v", e.Golden, err)
			}
			assertGolden(t, e, got, want)
		})
	}
}

// checkManifestEntry validates one manifest entry's compare-mode invariants and that
// its on-disk files exist. Split out of TestCorpusManifestComplete to keep that test's
// cyclomatic complexity within the gocyclo budget.
func checkManifestEntry(t *testing.T, e corpusEntry) {
	t.Helper()
	// Compare must be a known mode — an out-of-range value would slip past
	// TestCorpusGolden's switch with no assertion.
	if e.Compare != compareExact && e.Compare != compareNormalized {
		t.Errorf("manifest inconsistency: %s has unknown compare mode %d", e.Path, int(e.Compare))
	}
	// Invariant: synthetic ⇔ exact. A real fixture marked compareExact would be
	// overwritten by -update (D3 violation); a synthetic fixture marked
	// compareNormalized would skip byte-exact regression detection. Reject both.
	if e.Synthetic && e.Compare != compareExact {
		t.Errorf("manifest inconsistency: %s is Synthetic but not compareExact", e.Path)
	}
	if !e.Synthetic && e.Compare == compareExact {
		t.Errorf("manifest inconsistency: %s is real (non-synthetic) but compareExact — "+
			"-update would clobber its golden", e.Path)
	}
	if _, err := os.Stat(corpusPath(e.Path)); err != nil {
		t.Errorf("manifest fixture missing on disk: %s (%v)", e.Path, err)
	}
	if e.Golden != "" {
		if _, err := os.Stat(corpusPath(e.Golden)); err != nil {
			t.Errorf("manifest golden missing on disk: %s (%v)", e.Golden, err)
		}
	}
}

// TestCorpusNoGoldenFixtures guards the Golden == "" manifest entries against
// vacuous passes (adversarial-review finding): every such fixture must still
// open and paginate, and the hard-pdf negatives must still exhibit the
// extraction gap they document — replacement runes in the plain-text output.
// When future fallback-encoding work fixes one, this fails ON PURPOSE: promote
// the fixture to a golden-tested entry instead of relaxing the assertion.
func TestCorpusNoGoldenFixtures(t *testing.T) {
	for _, e := range corpusManifest {
		if e.Golden != "" {
			continue
		}
		t.Run(e.Path, func(t *testing.T) {
			r := loadCorpus(t, e)
			if n := r.NumPage(); n < 1 {
				t.Fatalf("NumPage = %d, want >= 1", n)
			}
			assertNoGoldenGap(t, e, r)
		})
	}
}

// assertNoGoldenGap asserts the anchored, non-vacuous gap/signal a Golden == ""
// fixture documents. Split out of TestCorpusNoGoldenFixtures to keep that test's
// cyclomatic complexity within the gocyclo budget (mirrors checkManifestEntry).
func assertNoGoldenGap(t *testing.T, e corpusEntry, r *Reader) {
	t.Helper()
	switch e.Path {
	case "hard/bea-dici0724.pdf":
		// Documented gap: subset fonts without usable ToUnicode —
		// text extracts as replacement runes.
		if !strings.ContainsRune(extractPlainText(t, r), '�') {
			t.Errorf("%s: documented gap (U+FFFD text) no longer reproduces — promote to a golden-tested entry", e.Path)
		}
	case "hard/irs-p1040-tax-tables-excerpt.pdf":
		// Documented gap: zero-advance glyph widths — words on the
		// first page carry W == 0 despite non-empty text.
		words, err := r.Page(1).Words()
		if err != nil {
			t.Fatalf("Words: %v", err)
		}
		zero := false
		for _, w := range words {
			if w.W == 0 && strings.TrimSpace(w.S) != "" {
				zero = true
				break
			}
		}
		if !zero {
			t.Errorf("%s: documented gap (zero-advance widths) no longer reproduces — promote to a golden-tested entry", e.Path)
		}
	default:
		if e.Feature == "hard-pdf" {
			t.Fatalf("%s: hard-pdf entry without an anchored gap assertion — add one here", e.Path)
		}
		// signals/ no-golden fixtures (image-only, panic-recovered streams)
		// are anchored via the shared signalExpectations map so they cannot
		// pass vacuously; reclassifying one needs no edit here.
		if strings.HasPrefix(e.Path, "signals/") {
			exp, ok := signalExpectations[e.Path]
			if !ok {
				t.Fatalf("%s: signals/ no-golden fixture without a signalExpectations entry", e.Path)
			}
			assertPageSignal(t, r, exp)
		}
	}
}

// TestCorpusManifestComplete checks that every manifest entry is internally consistent
// and present on disk, and that no committed .pdf under testdata/corpus lacks a manifest
// entry (an orphan fixture would look covered while being asserted on by nothing).
func TestCorpusManifestComplete(t *testing.T) {
	inManifest := map[string]bool{}
	for _, e := range corpusManifest {
		inManifest[filepath.ToSlash(e.Path)] = true
		checkManifestEntry(t, e)
	}
	err := filepath.WalkDir(corpusRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".pdf") {
			return nil
		}
		rel := filepath.ToSlash(strings.TrimPrefix(path, corpusRoot+string(filepath.Separator)))
		if !inManifest[rel] {
			t.Errorf("fixture on disk has no manifest entry: %s", rel)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk corpus: %v", err)
	}
}
