package pdf

import (
	"bytes"
	"context"
	"flag"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var updateGolden = flag.Bool("update", false, "regenerate synthetic golden + fixture files")

const corpusRoot = "testdata/corpus"

type compareMode int

const (
	compareExact      compareMode = iota // synthetic: byte-exact
	compareNormalized                    // real: whitespace-normalized substring
)

// corpusEntry is the single machine-readable source of truth for one fixture.
// README.md mirrors Source/License/Purpose for human readers.
type corpusEntry struct {
	Path      string      // relative to corpusRoot, e.g. "plaintext/hello-ascii.pdf"
	Golden    string      // relative golden path; "" = bench-only fixture (no golden)
	Synthetic bool        // true => generated by TestCorpusRegenerate
	Compare   compareMode // exact (synthetic) or normalized (real)
	Password  string      // for encrypted fixtures; "" otherwise
	Feature   string      // descriptive feature tag this fixture supports
	Source    string      // provenance URL or "synthetic"
	License   string      // "synthetic" | "US-Gov PD (17 USC 105)" | "CC0" | "Public domain (author d. >70y)"
	Purpose   string
}

// corpusManifest is the authoritative list. Adding a .pdf without an entry here fails
// TestCorpusManifestComplete.
var corpusManifest = []corpusEntry{
	{
		Path: "plaintext/hello-ascii.pdf", Golden: "plaintext/hello-ascii.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "corpus-baseline",
		Source: "synthetic", License: "synthetic",
		Purpose: "ASCII plain-text extraction baseline",
	},
	{
		Path: "styled/multifont.pdf", Golden: "styled/multifont.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "corpus-baseline",
		Source: "synthetic", License: "synthetic",
		Purpose: "Styled (multi-font) text extraction baseline",
	},
	// Real, verified, public-domain multilingual fixtures (already stored under
	// testdata/corpus/; see testdata/corpus/README.md for full provenance/license).
	// Golden snippets are hand-authored body-text passages; compareNormalized.
	{
		Path: "cjk/udhr-zh-hans.pdf", Golden: "cjk/udhr-zh-hans.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "corpus-baseline",
		Source: "OHCHR UDHR (chn)", License: "Public domain (UDHR)",
		Purpose: "Simplified Chinese extraction",
	},
	{
		Path: "cjk/irs-p850-zh-hant.pdf", Golden: "cjk/irs-p850-zh-hant.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "corpus-baseline",
		Source: "IRS Pub 850 EN-ZH-T", License: "US-Gov PD (17 USC 105)",
		Purpose: "Traditional Chinese extraction",
	},
	{
		Path: "cjk/udhr-ja.pdf", Golden: "cjk/udhr-ja.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "corpus-baseline",
		Source: "OHCHR UDHR (jpn)", License: "Public domain (UDHR)",
		Purpose: "Japanese extraction",
	},
	{
		Path: "cjk/udhr-ko.pdf", Golden: "cjk/udhr-ko.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "corpus-baseline",
		Source: "OHCHR UDHR (kkn)", License: "Public domain (UDHR)",
		Purpose: "Korean extraction",
	},
	{
		Path: "cyrillic/udhr-ru.pdf", Golden: "cyrillic/udhr-ru.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "encoding-fallback baseline",
		Source: "OHCHR UDHR (rus)", License: "Public domain (UDHR)",
		Purpose: "Russian (Cyrillic) extraction baseline for v0.8",
	},
	{
		Path: "bench/synthetic-multipage.pdf", Golden: "", Synthetic: true,
		Compare: compareExact, Feature: "corpus-baseline", Source: "synthetic", License: "synthetic",
		Purpose: "Synthetic multi-page benchmark corpus",
	},
	// Table-detection spike fixtures (acquired 2026-06-07; extraction verified
	// with Words()/Lines() probes before commit — provenance in README.md).
	{
		Path: "tables/nist-hb44-appc-2026.pdf", Golden: "tables/nist-hb44-appc-2026.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-spike",
		Source: "NIST Handbook 44 (2026) Appendix C", License: "US-Gov PD (17 USC 105)",
		Purpose: "Axis-aligned unit-conversion tables; clean text layer (spike accuracy gate)",
	},
	{
		Path: "tables/irs-p55b-2025-excerpt.pdf", Golden: "tables/irs-p55b-2025-excerpt.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-spike",
		Source: "IRS Data Book 2025 (Pub 55-B) pp. 40-55, qpdf excerpt", License: "US-Gov PD (17 USC 105)",
		Purpose: "Financial statistics tables; numeric columns extract, some labels unmapped",
	},
	// Cell-grid accuracy corpus: ground-truth grids in .cellgrid.tsv;
	// consumed by corpus_cellgrid_test.go.
	{
		Path: "tables/irs-db-t4-3-2025.pdf", Golden: "tables/irs-db-t4-3-2025.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "IRS Data Book 2025 (Pub 55-B) p.72 (Table 4-3 Appeals Workload), single-page qpdf excerpt",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Clean borderless cell-grid ground truth (10x4); partial text layer (some labels U+FFFD), numeric cells extract",
	},
	{
		Path: "tables/eia-aer-t3-1-2011.pdf", Golden: "tables/eia-aer-t3-1-2011.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "EIA Annual Energy Review 2011 Table 3.1 (Fossil Fuel Production Prices), eia.gov/totalenergy/data/annual/pdf/sec3_3.pdf",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Two-tier spanning-header cell-grid ground truth (45x10); special tokens R/(s)/2011P/en-dash; clean text layer",
	},
	{
		Path: "tables/bea-scb-gdp-2024-t1.pdf", Golden: "tables/bea-scb-gdp-2024-t1.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "BEA Survey of Current Business, 'GDP and the Economy: Third Estimates for the Fourth Quarter of 2024' (April 2025), Table 1 Real Gross Domestic Product and Related Measures, apps.bea.gov/scb/issues/2025/04-april/pdf/0425-gdp-economy.pdf (page 3)",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Cross-publisher (non-EIA) banded/group-ruled cell-grid ground truth (36x11, 3-tier header); alternating-fill row bands, group-only verticals; currently row-over-merged by Tables() — held-out Q2 generalization target",
	},
	{
		Path: "tables/tw-dgbas-happiness-2025.pdf", Golden: "tables/tw-dgbas-happiness-2025.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "Taiwan DGBAS, 表2 原國民幸福指數指標統計表 (Your Better Life Index indicators, Table 2), as of 2025-09-30, ws.dgbas.gov.tw",
		License: "TW OGDL v1 (政府資料開放授權 v1.0, CC-BY compatible)",
		Purpose: "Cross-publisher CJK (Traditional Chinese) per-cell-grid quality fixture (45x9, clean column split); held-out group-ruled+banded — exercises PR-1 inferColumnCuts v-edge column recovery (G1)",
	},
	{
		Path: "tables/de-destatis-insolvenzen-2023.pdf", Golden: "tables/de-destatis-insolvenzen-2023.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "Destatis (Statistisches Bundesamt) Fachserie 2 Reihe 4.1, Unternehmensinsolvenzen nach ausgewählten Wirtschaftsbereichen, Juni 2023, p.6, destatis.de",
		License: "DL-DE-BY-2.0 (Datenlizenz Deutschland Namensnennung 2.0)",
		Purpose: "Cross-publisher German per-cell-grid quality fixture (66x9, previously-G1-fused); held-out group-ruled+banded — the proven G1 column-collapse case PR-1 inferColumnCuts repairs",
	},
	{
		Path: "tables/epa-egrid2022-t1.pdf", Golden: "tables/epa-egrid2022-t1.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "EPA eGRID2022 Summary Tables, Table 1 (Subregion Output Emission Rates) p.2, epa.gov/system/files/documents/2024-01/egrid2022_summary_tables.pdf",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Held-out STROKE-bordered full-lattice cell-grid ground truth (31x17); ASCII-joined sub/superscript headers (CO2/CH4/N2O/NOX); bare-number data cells; companion egrid2022_summary_tables.xlsx",
	},
	{
		Path: "tables/irs-soi-inpre-t1-2022.pdf", Golden: "tables/irs-soi-inpre-t1-2022.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "IRS SOI Bulletin (Spring 2024), Table 1 (Individual Income Tax Returns, Preliminary Data, TY2022) p.6 (printed p.8), single-page qpdf excerpt, irs.gov/pub/irs-soi/soi-a-inpre-id2401.pdf",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Held-out RECT-bordered split-column cell-grid ground truth (51x6, cols 1-5 of an 11-col table); 3-tier rule-4 header; as-printed asterisks (* 5,178)/footnotes/negatives. Data fonts are subset TrueType (CIDFont+F1) whose ToUnicode declares a 2-byte codespace over 1-byte codes — the regression fixture for simple-font 1-byte ToUnicode decode; companion 22in01pl.xls",
	},
	{
		Path: "tables/fbi-nics-by-state-2026.pdf", Golden: "tables/fbi-nics-by-state-2026.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "FBI NICS Firearm Background Checks — Month/Year by State (Year 2026, Jan 1–May 31; snapshot 2026-06-16), fbi.gov/file-repository/cjis/nics_firearm_checks_-_month_year_by_state.pdf",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Held-out FULLY-RULED state-labeled cell-grid ground truth (56x14); held-out table-quality corpus (heldOut, scored by TestPublicTablesQualityCorpus). col0=State/Territory unique anchor; per-row checksum sum(months)=Grand Total. Char-spaced lattice extraction (content-clean via looseCell, verbatim-low by design). FBI overwrites the URL monthly — committed copy is a frozen snapshot",
	},
	{
		Path: "tables/hhs-aspe-vsl-2024.pdf", Golden: "tables/hhs-aspe-vsl-2024.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "HHS ASPE Standard Values for Regulatory Analysis 2024 (Jan 2024 Data Point), Table 1 (VSL Estimates by Year), p.2, single-page qpdf excerpt, aspe.hhs.gov/sites/default/files/documents/cd2a1348ea0777b1aa918089e4965b8c/standard-ria-values.pdf",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Held-out FULLY-RULED cell-grid ground truth (12x4); col0=Year unique numeric anchor. Second gate-bearing fully-ruled quality fixture (with FBI NICS) — the fully-ruled coverage gate flips hard on these two. Page yields a 1x4 title fragment + the 12x4 data table; largest-table selection scores the data table. Clean extraction (content+verbatim high)",
	},
	{
		Path: "tables/irs-p17zhs-rate-sched-2025.pdf", Golden: "tables/irs-p17zhs-rate-sched-2025.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "IRS Publication 17 (Simplified Chinese) 2025, Schedule X (single filers) of the 2025 tax rate schedules, PDF p.103, single-page qpdf excerpt, irs.gov/pub/irs-pdf/p17zhs.pdf",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Held-out FULLY-RULED CJK (Simplified Chinese) cell-grid ground truth (8x4); col0=$-bracket lower-bound unique anchor. CID-font/CJK diagnostic: bracket columns extract clean, the tax-formula columns mis-split. Page carries 4 schedules (X/Y-1/Y-2/Z); largest-table selection scores Schedule X. Class confirmed by rendered rule coverage; gate-independent (gate rests on NICS + ASPE)",
	},
	{
		Path: "tables/erp-2024-tb1-gdp-pctchg.pdf", Golden: "tables/erp-2024-tb1-gdp-pctchg.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "Economic Report of the President 2024, Table B-1 (Percent changes in real GDP, 1973-2023), PDF p.413, single-page qpdf excerpt, govinfo.gov/content/pkg/ERP-2024/pdf/ERP-2024.pdf",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Held-out RECT-bordered cell-grid ground truth (minimal 11x2 subset: Year anchor + GDP percent-change column, annual rows 1973-1982). Detector drops the open Year column and collapses the data rows -> ~0% substantive: the measured rect-bordered capability gap (gate HELD until the open-anchor-column + row-inference fix ships)",
	},
	{
		Path: "tables/erp-2024-tb2-gdp-contrib.pdf", Golden: "tables/erp-2024-tb2-gdp-contrib.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "Economic Report of the President 2024, Table B-2 (Contributions to percent change in real GDP, 1973-2023), PDF p.415, single-page qpdf excerpt, govinfo.gov/content/pkg/ERP-2024/pdf/ERP-2024.pdf",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Held-out RECT-bordered cell-grid ground truth (minimal 11x2 subset: Year anchor + GDP percent-change column, annual rows 1973-1982). Same capability gap as Table B-1 (Year column dropped, rows collapsed -> ~0% substantive); second rect-bordered held-out fixture. Single-publisher (both ERP/CEA) — cross-publisher generalization NOT demonstrated",
	},
	{
		Path: "tables/nass-cropan-2024-planted-harvested.pdf", Golden: "tables/nass-cropan-2024-planted-harvested.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-cellgrid",
		Source:  "USDA NASS Crop Production 2024 Summary (January 2025), 'Principal Crops Area Planted and Harvested - States and United States: 2022-2024', page 7, nass.usda.gov/Publications/Todays_Reports/reports/cropan25.pdf (single-page excerpt)",
		License: "US-Gov PD (17 USC 105)",
		Purpose: "Cross-publisher (USDA, non-CEA/ERP) held-out RECT-bordered cell-grid ground truth (53x7, 3-tier header); open dot-leader State anchor, vertical column rules + outer frame, zero interior row rules; clean text layer",
	},
	// Table-detection false-positive gate fixtures: dense 3-column Federal
	// Register notices with ZERO tables — a detector must return nothing here.
	{
		Path: "multicolumn/fr-2024-06543.pdf", Golden: "multicolumn/fr-2024-06543.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-spike",
		Source: "Federal Register 89 FR 21528 (2024-06543), govinfo.gov", License: "US-Gov PD (17 USC 105)",
		Purpose: "Dense 3-column body text, no tables (spike false-positive gate)",
	},
	{
		Path: "multicolumn/fr-2024-01353.pdf", Golden: "multicolumn/fr-2024-01353.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "table-spike",
		Source: "Federal Register 89 FR 4633 (2024-01353), govinfo.gov", License: "US-Gov PD (17 USC 105)",
		Purpose: "Dense 3-column body text, no tables (spike false-positive gate)",
	},
	// Hard-PDF fixtures discovered during table-fixture acquisition: real
	// US-Gov financial PDFs that defeat current extraction; no goldens — they
	// document the gap until future fallback-encoding work closes it.
	{
		Path: "hard/bea-dici0724.pdf", Golden: "hard/bea-dici0724.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "hard-pdf",
		Source: "BEA Direct Investment by Country and Industry (Jul 2024)", License: "US-Gov PD (17 USC 105)",
		Purpose: "Subset fonts; T* line-moves previously mis-decoded to U+FFFD under a 2-byte CMap (fixed) — now extracts with zero replacement runes across all 12 pages; locked by golden snippets + a document-wide no-U+FFFD assertion (TestCorpusBeaDiciNoReplacementRunes)",
	},
	{
		Path: "hard/irs-p1040-tax-tables-excerpt.pdf", Golden: "hard/irs-p1040-tax-tables-excerpt.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "hard-pdf",
		Source: "IRS Pub 1040 Tax Tables pp. 3-4, qpdf excerpt", License: "US-Gov PD (17 USC 105)",
		Purpose: "Type0/CIDFontType2 with /W + /DW: formerly zero-advance widths (Width path ignored CIDFont metrics); fixed by effectiveWidth reading /DW (per-CID /W deferred behind n++ two-byte-code fix).",
	},
	// Real, public-domain AcroForm fixtures (acquired 2026-06-11). Both are BLANK
	// government forms — Reader.Fields() had only ever met hand-crafted synthetic
	// fixtures (forms_test.go); these lock it against REAL field-tree structure,
	// qualified names, types, and generator quirks. The text Golden here sentinels
	// cross-page body labels in the static label layer (GetPlainText) — not just the
	// page-1 header — so a regression that drops later pages or body text fails it;
	// the rotated-run path is gated separately by TestRotatedTextWarningCorpusWide.
	// The AcroForm field inventory itself is locked
	// separately by TestCorpusFormFixtures against a .fields-golden.txt. No PII —
	// the forms carry no entered data, and CV-071's document metadata was stripped
	// (qpdf --remove-info --remove-metadata) to drop a template author's personal
	// name from /Info + XMP; the AcroForm body is unmodified and both goldens are
	// byte-identical before/after (see testdata/corpus/README.md).
	{
		Path: "forms/irs-f1040-2025.pdf", Golden: "forms/irs-f1040-2025.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "acroform",
		Source: "IRS Form 1040 (2025), irs.gov/pub/irs-pdf/f1040.pdf", License: "US-Gov PD (17 USC 105)",
		Purpose: "Blank IRS LiveCycle form: 199 fields, deep dotted qualified names (maxDepth 6), Adobe Designer quirks",
	},
	{
		Path: "forms/uscourts-cv071-civil-cover.pdf", Golden: "forms/uscourts-cv071-civil-cover.golden.txt",
		Synthetic: false, Compare: compareNormalized, Feature: "acroform",
		Source: "US District Court C.D. Cal. Civil Cover Sheet CV-071, cacd.uscourts.gov", License: "US-Gov PD (17 USC 105)",
		Purpose: "Blank court form: real /Parent field tree + /DA chains; Acrobat-derived /T label names",
	},
	// Synthetic extraction-readiness signal fixtures.
	// Consumers: the extraction quality score and the image/scanned-page classifier.
	// Golden cells reflect the EMPIRICAL classification (probe run at implementation):
	// image-only pages and the truncated stream extract no usable plain text (Golden:"");
	// the rest extract deterministic text and are byte-locked. wantErr/HasText live in
	// signalExpectations (corpus_signals_test.go), keyed on ExtractionSummary, which can
	// differ from the GetPlainText-keyed Golden decision (truncated: Golden:"" yet
	// ExtractionSummary recovers to HasText=true — a silent-ok gap the quality score will close).
	{
		Path: "signals/image-full-bleed.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "signal-image-classifier",
		Source: "synthetic", License: "synthetic",
		Purpose: "Full-bleed image-only page (coverage ~1.0); image_only signal",
	},
	{
		Path: "signals/image-thumbnail.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "signal-image-classifier",
		Source: "synthetic", License: "synthetic",
		Purpose: "Thumbnail-only image page (coverage ~0.0074); v1 indistinguishable from full-bleed",
	},
	{
		Path: "signals/image-thumbnail-text.pdf", Golden: "signals/image-thumbnail-text.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-image-classifier",
		Source: "synthetic", License: "synthetic",
		Purpose: "Small image + body text; mixed page, not image-only",
	},
	{
		Path: "signals/text-artifact-only.pdf", Golden: "signals/text-artifact-only.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-image-classifier",
		Source: "synthetic", License: "synthetic",
		Purpose: "Artifact-only sparse text (page number at extremity); fires sparse_text warning",
	},
	{
		Path: "signals/text-numeric-center.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "signal-image-classifier",
		Source: "synthetic", License: "synthetic",
		Purpose: "Page-number token at page centre; text signal, NO sparse_text warning (margin-band negative)",
	},
	{
		Path: "signals/malformed-unclosed-bt.pdf", Golden: "signals/malformed-unclosed-bt.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-malformed-stream",
		Source: "synthetic", License: "synthetic",
		Purpose: "Unclosed BT (no ET); tolerated, deterministic partial extraction, no panic",
	},
	{
		Path: "signals/malformed-mismatched-qq.pdf", Golden: "signals/malformed-mismatched-qq.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-malformed-stream",
		Source: "synthetic", License: "synthetic",
		Purpose: "Excess Q (q/Q imbalance); tolerated, deterministic extraction, no panic",
	},
	{
		Path: "signals/malformed-truncated.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "signal-malformed-stream",
		Source: "synthetic", License: "synthetic",
		// Realized as an empty-TJ operator (deterministic panic trigger), NOT a
		// byte-level cut-off stream — slice-1 ships no genuinely-truncated fixture.
		Purpose: "Malformed operator (TJ w/o array); GetPlainText errors, ExtractionSummary recovers (silent-ok gap), no panic",
	},
	// Fallback decode-path fixtures (consumer: the fallback encoding framework).
	// One per no-/ToUnicode decode-path class. Golden cells reflect the EMPIRICAL
	// classification (probe run at implementation): all six extract deterministic
	// text and are byte-locked; the document-scoped warning each fires is asserted
	// by TestCorpusDecodePathFixtures (corpus_decodepath_test.go).
	{
		Path: "encoding/predefined-identity.pdf", Golden: "encoding/predefined-identity.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-decode-path",
		Source: "synthetic", License: "synthetic",
		Purpose: "Predefined CMap (/Identity-H) without ToUnicode → missing_tounicode",
	},
	{
		Path: "encoding/charset-shiftjis.pdf", Golden: "encoding/charset-shiftjis.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-decode-path",
		Source: "synthetic", License: "synthetic",
		Purpose: "Shift-JIS charset fallback (/90ms-RKSJ-H) → fallback_encoding",
	},
	{
		Path: "encoding/ucs2-be.pdf", Golden: "encoding/ucs2-be.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-decode-path",
		Source: "synthetic", License: "synthetic",
		Purpose: "UCS-2 BE predefined CMap (/UniGB-UCS2-H) → fallback_encoding",
	},
	{
		Path: "encoding/identity-tounicode-ucs2.pdf", Golden: "encoding/identity-tounicode-ucs2.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-decode-path",
		Source: "synthetic", License: "synthetic",
		Purpose: "Type0 /Encoding /Identity-H with /ToUnicode AS A NAME /Identity-H (Identity ordering): 2-byte codes are UCS-2 BE Unicode → decoded directly (else garbled ~50% U+FFFD). Public-surface lock for the Identity-H ToUnicode-Name fix.",
	},
	{
		Path: "encoding/cid-japan1-no-tounicode.pdf", Golden: "encoding/cid-japan1-no-tounicode.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-decode-path",
		Source: "synthetic", License: "synthetic",
		Purpose: "Type0 /Encoding /Identity-H, Adobe-Japan1 ordering, NO /ToUnicode: 2-byte codes are CIDs → decoded via the Adobe-Japan1 CID→Unicode map (encSourceCIDMap), else garbled. Public-surface lock for the CID-map fix.",
	},
	{
		Path: "encoding/differences-partial.pdf", Golden: "encoding/differences-partial.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-decode-path",
		Source: "synthetic", License: "synthetic",
		Purpose: "Encoding dict /Differences with an unmappable glyph name → missing_glyph_mapping",
	},
	{
		Path: "encoding/unknown-name.pdf", Golden: "encoding/unknown-name.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-decode-path",
		Source: "synthetic", License: "synthetic",
		Purpose: "Unknown /Encoding name → unsupported_encoding (pdfDoc fallback)",
	},
	{
		Path: "encoding/unmapped-glyph.pdf", Golden: "encoding/unmapped-glyph.golden.txt",
		Synthetic: true, Compare: compareExact, Feature: "signal-decode-path",
		Source: "synthetic", License: "synthetic",
		Purpose: "ToUnicode CMap under-covering its codespace → U+FFFD in output (silent today)",
	},
	// Rotated + vertical warning fixtures (no golden; warning-level only). Consumer:
	// fallback-encoding risk warnings; also the fixture half of the rotated/vertical
	// geometry gate.
	{
		Path: "geometry/rotated-90.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "signal-geometry",
		Source: "synthetic", License: "synthetic",
		Purpose: "90°-rotated Tm run (FontSize=Trm[0][0]=0); fires WarningRotatedText (the rotated-text risk lock; contrast to page-rotate-90.pdf, same content + /Rotate 90, which cancels it)",
	},
	{
		Path: "geometry/vertical-cmap.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "signal-geometry",
		Source: "synthetic", License: "synthetic",
		Purpose: "Vertical -V CMap (/UniJIS-UCS2-V); fires fallback+vertical warnings; advance now vertical (single glyph: unobservable here)",
	},
	{
		Path: "geometry/page-rotate-90.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "signal-geometry",
		Source: "synthetic", License: "synthetic",
		Purpose: "page /Rotate 90 honored: the rotated-90 content (Tm 0 1 -1 0) plus /Rotate 90 cancels to an upright display-space baseline; FontSize recovers, no rotated-text warning (contrast to rotated-90.pdf, same content, no /Rotate)",
	},
	// Table false-positive discriminator: isolated shaded prose bands + callout boxes.
	// No-table fixture: TestLatticeFalsePositiveGate is the real anchor (0-FP gate).
	{
		Path: "discriminator/shaded-non-table.pdf", Golden: "",
		Synthetic: true, Compare: compareExact, Feature: "table-fp-discriminator",
		Source: "synthetic", License: "synthetic",
		Purpose: "Six isolated alternating-shaded prose bands + two isolated callout boxes (all fill rects non-touching, so no closed lattice forms); zero tables — discriminator for inferFillBandedRows false-positive gate",
	},
}

func corpusPath(rel string) string { return filepath.Join(corpusRoot, filepath.FromSlash(rel)) }

func loadCorpus(t *testing.T, e corpusEntry) *Reader {
	t.Helper()
	data, err := os.ReadFile(corpusPath(e.Path))
	if err != nil {
		t.Fatalf("read fixture %s: %v", e.Path, err)
	}
	if e.Password != "" {
		r, err := NewReaderEncrypted(bytes.NewReader(data), int64(len(data)), func() string { return e.Password })
		if err != nil {
			t.Fatalf("open encrypted fixture %s: %v", e.Path, err)
		}
		return r
	}
	r, err := OpenBytes(data)
	if err != nil {
		t.Fatalf("open fixture %s: %v", e.Path, err)
	}
	return r
}

func extractPlainText(t *testing.T, r *Reader) string {
	t.Helper()
	rd, err := r.GetPlainText(context.Background())
	if err != nil {
		t.Fatalf("GetPlainText: %v", err)
	}
	b, err := io.ReadAll(rd)
	if err != nil {
		t.Fatalf("read extracted text: %v", err)
	}
	return string(b)
}

var wsRun = strings.NewReplacer("\r", " ", "\n", " ", "\t", " ")

func normalize(s string) string {
	return strings.Join(strings.Fields(wsRun.Replace(s)), " ")
}

// assertGolden checks extraction output `got` against golden bytes `want` per the
// entry's compare mode. Split out of TestCorpusGolden to keep that test's cyclomatic
// complexity within the gocyclo budget.
func assertGolden(t *testing.T, e corpusEntry, got string, want []byte) {
	t.Helper()
	switch e.Compare {
	case compareExact:
		if got != string(want) {
			t.Errorf("%s: exact mismatch\n got: %q\nwant: %q", e.Path, got, string(want))
		}
	case compareNormalized:
		// The golden holds one required snippet per non-empty line; EVERY one must
		// appear in the normalized extraction. Multiple body-text snippets (not just a
		// title) make this a real regression sentinel: an extractor that returns only
		// the heading but drops body text fails. An empty or whitespace-only golden
		// yields zero snippets and is rejected, because strings.Contains(x, "") is
		// vacuously true (D2/D3).
		gotNorm := normalize(got)
		var checked int
		for line := range strings.SplitSeq(string(want), "\n") {
			snip := normalize(line)
			if snip == "" {
				continue
			}
			checked++
			if !strings.Contains(gotNorm, snip) {
				t.Errorf("%s: required snippet not found in extraction\nsnippet: %q\ngot: %q",
					e.Path, snip, gotNorm)
			}
		}
		if checked == 0 {
			t.Fatalf("%s: normalized golden %s has no non-empty snippets — refusing to pass vacuously",
				e.Path, e.Golden)
		}
	default:
		// An out-of-range Compare would otherwise extract + read the golden but run no
		// assertion, making the entry look covered while regressions stay invisible.
		// TestCorpusManifestComplete also rejects this statically.
		t.Fatalf("%s: unknown compare mode %d", e.Path, int(e.Compare))
	}
}

func TestCorpusGolden(t *testing.T) {
	t.Parallel()
	for _, e := range corpusManifest {
		if e.Golden == "" {
			continue // bench-only fixture
		}
		t.Run(e.Path, func(t *testing.T) {
			t.Parallel()
			got := extractPlainText(t, loadCorpus(t, e))
			goldenFile := corpusPath(e.Golden)
			// -update regenerates synthetic+exact goldens only — never real/normalized
			// goldens, to avoid leaking PII from a real PDF's body (D3). The Synthetic
			// guard is belt-and-braces: a real entry mislabelled compareExact would
			// otherwise have its hand-authored golden overwritten by full extraction.
			// TestCorpusManifestComplete additionally rejects that mislabelling.
			if *updateGolden && e.Synthetic && e.Compare == compareExact {
				if err := os.WriteFile(goldenFile, []byte(got), 0o600); err != nil {
					t.Fatalf("update golden %s: %v", e.Golden, err)
				}
				return
			}
			//nolint:gosec // G304: goldenFile is a fixed corpus path from the manifest, not user input
			want, err := os.ReadFile(goldenFile)
			if err != nil {
				t.Fatalf("read golden %s: %v", e.Golden, err)
			}
			assertGolden(t, e, got, want)
		})
	}
}

// checkManifestEntry validates one manifest entry's compare-mode invariants and that
// its on-disk files exist. Split out of TestCorpusManifestComplete to keep that test's
// cyclomatic complexity within the gocyclo budget.
func checkManifestEntry(t *testing.T, e corpusEntry) {
	t.Helper()
	// Compare must be a known mode — an out-of-range value would slip past
	// TestCorpusGolden's switch with no assertion.
	if e.Compare != compareExact && e.Compare != compareNormalized {
		t.Errorf("manifest inconsistency: %s has unknown compare mode %d", e.Path, int(e.Compare))
	}
	// Invariant: synthetic ⇔ exact. A real fixture marked compareExact would be
	// overwritten by -update (D3 violation); a synthetic fixture marked
	// compareNormalized would skip byte-exact regression detection. Reject both.
	if e.Synthetic && e.Compare != compareExact {
		t.Errorf("manifest inconsistency: %s is Synthetic but not compareExact", e.Path)
	}
	if !e.Synthetic && e.Compare == compareExact {
		t.Errorf("manifest inconsistency: %s is real (non-synthetic) but compareExact — "+
			"-update would clobber its golden", e.Path)
	}
	if _, err := os.Stat(corpusPath(e.Path)); err != nil {
		t.Errorf("manifest fixture missing on disk: %s (%v)", e.Path, err)
	}
	if e.Golden != "" {
		if _, err := os.Stat(corpusPath(e.Golden)); err != nil {
			t.Errorf("manifest golden missing on disk: %s (%v)", e.Golden, err)
		}
	}
}

// TestCorpusNoGoldenFixtures guards the Golden == "" manifest entries against
// vacuous passes (adversarial-review finding): every such fixture must still
// open and paginate, and the hard-pdf negatives must still exhibit the
// extraction gap they document — replacement runes in the plain-text output.
// When future fallback-encoding work fixes one, this fails ON PURPOSE: promote
// the fixture to a golden-tested entry instead of relaxing the assertion.
func TestCorpusNoGoldenFixtures(t *testing.T) {
	t.Parallel()
	for _, e := range corpusManifest {
		if e.Golden != "" {
			continue
		}
		t.Run(e.Path, func(t *testing.T) {
			t.Parallel()
			r := loadCorpus(t, e)
			if n := r.NumPage(); n < 1 {
				t.Fatalf("NumPage = %d, want >= 1", n)
			}
			assertNoGoldenGap(t, e, r)
		})
	}
}

// assertNoGoldenGap asserts the anchored, non-vacuous gap/signal a Golden == ""
// fixture documents. Split out of TestCorpusNoGoldenFixtures to keep that test's
// cyclomatic complexity within the gocyclo budget (mirrors checkManifestEntry).
func assertNoGoldenGap(t *testing.T, e corpusEntry, r *Reader) {
	t.Helper()
	switch e.Path {
	default:
		if e.Feature == "hard-pdf" {
			t.Fatalf("%s: hard-pdf entry without an anchored gap assertion — add one here", e.Path)
		}
		// signals/ (slice 1) and geometry/ (slice 2) no-golden fixtures are
		// anchored via their shared expectations maps so they cannot pass
		// vacuously; reclassifying one needs no edit here. See anchorNoGoldenSignal.
		anchorNoGoldenSignal(t, e, r)
	}
}

// TestCorpusManifestComplete checks that every manifest entry is internally consistent
// and present on disk, and that no committed .pdf under testdata/corpus lacks a manifest
// entry (an orphan fixture would look covered while being asserted on by nothing).
func TestCorpusManifestComplete(t *testing.T) {
	inManifest := map[string]bool{}
	for _, e := range corpusManifest {
		inManifest[filepath.ToSlash(e.Path)] = true
		checkManifestEntry(t, e)
	}
	err := filepath.WalkDir(corpusRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".pdf") {
			return nil
		}
		rel := filepath.ToSlash(strings.TrimPrefix(path, corpusRoot+string(filepath.Separator)))
		if !inManifest[rel] {
			t.Errorf("fixture on disk has no manifest entry: %s", rel)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk corpus: %v", err)
	}
}
