package pdf

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"strings"
	"testing"
)

// aesCBCNoPadEncrypt is the encrypt counterpart of aesCBCNoPad (zero IV, no pad).
func aesCBCNoPadEncrypt(key, data []byte) []byte {
	block, _ := aes.NewCipher(key)
	out := make([]byte, len(data))
	cipher.NewCBCEncrypter(block, make([]byte, aes.BlockSize)).CryptBlocks(out, data)
	return out
}

// aes256Fixture builds a V=5 /Encrypt dict for revision rev whose user password
// is `password` and owner password is "owner", wrapping fileKey (32 bytes).
// Salts are fixed for determinism.
func aes256Fixture(rev int64, password string, fileKey []byte) dict {
	up := saslPrep(password)
	uv, uk := []byte("UVALSALT"), []byte("UKEYSALT")
	U := concat(hashAES256(rev, up, uv, nil), uv, uk)               // 48 bytes
	UE := aesCBCNoPadEncrypt(hashAES256(rev, up, uk, nil), fileKey) // 32 bytes

	op := saslPrep("owner")
	ov, ok := []byte("OVALSALT"), []byte("OKEYSALT")
	O := concat(hashAES256(rev, op, ov, U), ov, ok)               // 48 bytes
	OE := aesCBCNoPadEncrypt(hashAES256(rev, op, ok, U), fileKey) // 32 bytes

	return dict{
		name("Filter"): name("Standard"),
		name("V"):      int64(5),
		name("R"):      rev,
		name("O"):      string(O),
		name("U"):      string(U),
		name("OE"):     string(OE),
		name("UE"):     string(UE),
		name("P"):      int64(-4),
		name("Length"): int64(256),
		name("CF"): dict{name("StdCF"): dict{
			name("CFM"):       name("AESV3"),
			name("AuthEvent"): name("DocOpen"),
			name("Length"):    int64(32),
		}},
		name("StmF"): name("StdCF"),
		name("StrF"): name("StdCF"),
	}
}

func newAES256Reader(rev int64, fileKey []byte) *Reader {
	return &Reader{
		f:   bytes.NewReader(nil),
		end: 0,
		trailer: dict{
			name("Encrypt"): aes256Fixture(rev, "", fileKey),
			name("ID"):      array{strings.Repeat("\x01", 16), strings.Repeat("\x01", 16)},
		},
	}
}

func TestDecryptAES256R5(t *testing.T) { testDecryptAES256(t, 5) }
func TestDecryptAES256R6(t *testing.T) { testDecryptAES256(t, 6) }

func testDecryptAES256(t *testing.T, rev int64) {
	t.Helper()
	fileKey := make([]byte, 32)
	for i := range fileKey {
		fileKey[i] = byte(i + 1)
	}

	// User (empty) password path.
	r := newAES256Reader(rev, fileKey)
	if err := r.initEncrypt(""); err != nil {
		t.Fatalf("R=%d user initEncrypt: %v", rev, err)
	}
	if !r.aes256 || !r.useAES {
		t.Fatalf("R=%d: want aes256+useAES, got aes256=%v useAES=%v", rev, r.aes256, r.useAES)
	}
	if !bytes.Equal(r.key, fileKey) {
		t.Fatalf("R=%d: recovered key %x, want %x", rev, r.key, fileKey)
	}

	// Owner password path (user "" fails the empty-password validation hash).
	ro := newAES256Reader(rev, fileKey)
	if err := ro.initEncrypt("owner"); err != nil {
		t.Fatalf("R=%d owner initEncrypt: %v", rev, err)
	}
	if !bytes.Equal(ro.key, fileKey) {
		t.Fatalf("R=%d owner: recovered key %x, want %x", rev, ro.key, fileKey)
	}

	// Per-object string decryption uses the file key DIRECTLY (objptr ignored).
	plaintext := "AES-256 secret string"
	enc := aesCBCEncrypt(r.key, []byte(plaintext)) // 32-byte key → AES-256
	got := decryptString(r.key, r.useAES, r.aes256, objptr{id: 7, gen: 0}, string(enc))
	if got != plaintext {
		t.Errorf("R=%d: decryptString = %q, want %q", rev, got, plaintext)
	}
}

func TestDecryptAES256WrongPassword(t *testing.T) {
	fileKey := make([]byte, 32)
	r := newAES256Reader(6, fileKey)
	if err := r.initEncrypt("definitely-wrong"); err != ErrInvalidPassword {
		t.Errorf("wrong password: got %v, want ErrInvalidPassword", err)
	}
}

// TestDecryptAES256MalformedLength covers the exact-length rejection branch:
// a V=5 /Encrypt dict whose O/U/OE/UE field is not exactly 48/48/32/32 bytes
// must error rather than slice out of bounds or silently mis-derive.
func TestDecryptAES256MalformedLength(t *testing.T) {
	for _, tc := range []struct {
		field string
		val   string
	}{
		{"U", string(make([]byte, 47))}, // one short of 48
		{"O", string(make([]byte, 49))}, // one over 48
		{"UE", string(make([]byte, 31))},
		{"OE", string(make([]byte, 33))},
	} {
		fileKey := make([]byte, 32)
		enc := aes256Fixture(6, "", fileKey)
		enc[name(tc.field)] = tc.val
		r := &Reader{f: bytes.NewReader(nil), trailer: dict{name("Encrypt"): enc}}
		if err := r.initEncrypt(""); err == nil {
			t.Errorf("malformed %s length %d: want error, got nil", tc.field, len(tc.val))
		}
	}
}

// TestAESCBCNoPadKAT pins aesCBCNoPad (the UE/OE key unwrap) against an
// INDEPENDENT AES-256-CBC zero-IV no-padding vector computed with openssl, so a
// bug coupled between aesCBCNoPad and the fixtures' aesCBCNoPadEncrypt cannot
// hide behind the roundtrip tests. Generated by:
//
//	printf '0123456789abcdef0123456789abcdef' | openssl enc -aes-256-cbc -nopad \
//	  -K 000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f \
//	  -iv 00000000000000000000000000000000 | xxd -p
func TestAESCBCNoPadKAT(t *testing.T) {
	key := []byte{
		0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
		0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
	}
	ct := []byte{
		0xd8, 0xc9, 0x57, 0x58, 0xe3, 0x35, 0x3e, 0x53, 0x0f, 0xa5, 0x2b, 0xd1, 0x0e, 0x73, 0xb9, 0x86,
		0x68, 0x60, 0xb2, 0xed, 0x71, 0x1f, 0x57, 0xfa, 0xa5, 0x6e, 0x41, 0xd7, 0xe0, 0xe8, 0x4a, 0xa2,
	}
	want := []byte("0123456789abcdef0123456789abcdef")
	if got := aesCBCNoPad(key, ct); !bytes.Equal(got, want) {
		t.Errorf("aesCBCNoPad KAT: got %x, want %x", got, want)
	}
}

// TestHash2BKAT pins the revision hash against an INDEPENDENT known-answer
// vector so a bug in hash2B/hashAES256 cannot be masked by the roundtrip
// fixtures (which run the same code on both sides).
//
// Source: qpdf qtest file enc-XI-R6,V5,U=wwwww,O=wwwww.pdf @ commit 9ebb55a
// (Apache-2.0). The 48-byte /U and /O were extracted from the (unencrypted)
// /Encrypt dict of that file; bytes were generated by qpdf's C++ AESV3
// encryptor and re-verified with an independent pycryptodome+hashlib script
// (NOT this code). The R=5 vector is plain SHA-256, cross-checked with
// openssl/shasum.
func TestHash2BKAT(t *testing.T) {
	const pw = "wwwww" // R=6, V=5

	// /U — 48 bytes: [0:32]=validation hash, [32:40]=validation salt, [40:48]=key salt
	U := []byte{0xae, 0xb5, 0xac, 0x20, 0x58, 0xf4, 0xd3, 0x69, 0x62, 0x6e, 0x09, 0x13, 0x06, 0xb8, 0x2f, 0x75, 0x6b, 0x8d, 0x03, 0x0c, 0x0b, 0x46, 0x3b, 0xb5, 0xef, 0xbb, 0x6a, 0xc6, 0x1f, 0xa2, 0xce, 0x9b, 0x95, 0xfa, 0xe0, 0x84, 0x49, 0x63, 0x8c, 0x55, 0xc9, 0x0a, 0x33, 0xf2, 0x1c, 0xdb, 0xfc, 0x02}
	// /O — 48 bytes, same layout
	O := []byte{0xd7, 0x1a, 0x46, 0x9f, 0xf2, 0xe4, 0x82, 0xab, 0xdf, 0x5f, 0xc3, 0xb4, 0x95, 0x8b, 0x41, 0x91, 0x3f, 0x3f, 0x6a, 0x37, 0xb2, 0x43, 0xa6, 0xae, 0xcd, 0x4d, 0x21, 0x0b, 0x89, 0x80, 0x30, 0xf6, 0x0a, 0x3e, 0x0f, 0x56, 0xe5, 0x75, 0xc4, 0x28, 0xeb, 0x96, 0x15, 0x67, 0x77, 0x1c, 0x04, 0x2c}

	// R=6 user path (udata=nil) — Algorithm 2.B against real qpdf-generated data.
	if !bytes.Equal(hashAES256(6, []byte(pw), U[32:40], nil), U[:32]) {
		t.Error("R=6 Algorithm 2.B user KAT failed")
	}
	// R=6 owner path (udata = full 48-byte U) — exercises the udata branch.
	if !bytes.Equal(hashAES256(6, []byte(pw), O[32:40], U), O[:32]) {
		t.Error("R=6 Algorithm 2.B owner KAT failed")
	}
	// R=5 path = plain SHA-256("wwwww" ‖ U[32:40]); pinned with openssl/shasum.
	r5 := []byte{0x7f, 0x14, 0x48, 0xf8, 0x54, 0xf0, 0x67, 0x79, 0x78, 0x69, 0x74, 0x03, 0x21, 0xe8, 0xd3, 0xbf, 0x3a, 0x34, 0x1b, 0x0c, 0x10, 0xfd, 0x01, 0xa0, 0xb0, 0xab, 0xe9, 0x35, 0xfc, 0xa8, 0xf4, 0xe1}
	if !bytes.Equal(hashAES256(5, []byte(pw), U[32:40], nil), r5) {
		t.Error("R=5 SHA-256 KAT failed")
	}
}
